name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        group: [check_release, link_check]
      fail-fast: false
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-pip-
      - name: Cache checked links
        if: ${{ matrix.group == 'link_check' }}
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/pytest-link-check
          key: ${{ runner.os }}-linkcheck-${{ hashFiles('**/*.md', '**/*.rst') }}-md-links
          restore-keys: |
            ${{ runner.os }}-linkcheck-
      - name: Upgrade packaging dependencies
        run: |
          pip install --upgrade pip setuptools wheel --user
      - name: Install Dependencies
        run: |
          pip install -e .
      - name: Check Release
        if: ${{ matrix.group == 'check_release' }}
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@45ee32c387085d5f1df41da443ade8b952a9dac6 # v2
        with:
          version_spec: 100.100.100
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Link Check
        if: ${{ matrix.group == 'link_check' }}
        uses: jupyterlab/maintainer-tools/.github/actions/check-links@d5b08e36724fe4271b4751cc0d84c80c2e5c982c # v1
        with:
          ignore_glob: nbclassic/static/components/**/*.md docs-translations/*/*.md
          ignore_links: http://127.0.0.1
