name: Docs Tests
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  python-version: '3.11'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install Python ${{ env.python-version }}
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ env.python-version }}
        architecture: 'x64'
    - name: Upgrade packaging dependencies
      run: |
        pip install --upgrade pip setuptools wheel
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ env.python-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ env.python-version }}-
          ${{ runner.os }}-pip-
    - name: Install the Python dependencies
      run: |
        pip install -e .[test] codecov
        pip install -r docs/doc-requirements.txt
    - name: Install pandoc
      uses: pandoc/actions/setup@54978b2465cef52a89f0e50a71d1397b1c25b469 # v1.1.0
      with:
        version: 3.6.4
    - name: List installed packages
      run: |
        pip freeze
        pip check
    - name: Run tests on documentation
      run: |
        EXIT_STATUS=0
        make -C docs/ html || EXIT_STATUS=$?
        cd docs/source && pytest --nbval --current-env .. || EXIT_STATUS=$?
        exit $EXIT_STATUS
