name: Enforce PR label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: enforce-triage-label
        uses: jupyterlab/maintainer-tools/.github/actions/enforce-label@d5b08e36724fe4271b4751cc0d84c80c2e5c982c # v1
